<?php

class ReportTemplate {
    /*
     * header
     * SummarySection
     * topSection
     * pass/fail/incomplete/validationFail
     * bottomSection
     * footer
     */

    public function header() {
        $html = '<!DOCTYPE html>
                    <html>
                        <head>
                            <title>Auto_API Report</title>
                            <meta name="viewport" content="width=device-width, initial-scale=1">
                            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
                            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
                            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
                            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
                        </head>
                        <body>

                            <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top justify-content-center">
                                <a class="navbar-brand" target="_blank" href="https://github.com/ankitmalikg2/Auto_API">Auto_API Report</a>
                            </nav>';
        return $html;
    }

    public function footer() {
        $html='</body></html>';
        return $html;
    }
    
    public function summarySection($total,$pass,$fail,$validationFail,$incomplete){
        $html='<div class="container col-md-4" style="margin-top:80px">
            <h2 class="text-center">Summary</h2>
            <div class="d-flex flex-column mb-3">
                <div class="p-2 bg-light text-danger">
                    <div class="row">
                        <div class="col"><b>Total</b></div>
                        <div class="col text-right"><b>'.$total.'</b></div>
                    </div>
                </div>
                <div class="p-2 bg-success text-white">
                    <div class="row">
                        <div class="col"><b>Success</b></div>
                        <div class="col text-right"><b>'.$pass.'</b></div>
                    </div>
                </div>
                <div class="p-2 bg-danger text-white">
                    <div class="row">
                        <div class="col"><b>Failure</b></div>
                        <div class="col text-right"><b>'.$fail.'</b></div>
                    </div>
                </div>
                <div class="p-2 bg-warning">
                    <div class="row">
                        <div class="col"><b>Validation Failure</b></div>
                        <div class="col text-right"><b>'.$validationFail.'</b></div>
                    </div>
                </div>
                <div class="p-2 bg-dark text-white">
                    <div class="row">
                        <div class="col"><b>Incomplete</b></div>
                        <div class="col text-right"><b>'.$incomplete.'</b></div>
                    </div>
                </div>
            </div>
        </div>
        <hr>';
        return $html;
    }

    public function topSection() {
        $html='<div class="container">
            <h2 class="text-center">Auto_API Detailed Report</h2>
            <p class="text-center"><strong>Note:</strong> This report is generated by Auto_API tool. If you face any issue then contact <a target="_blank"  href="https://github.com/ankitmalikg2/Auto_API/issues">here</a></p>
            <div id="accordion">';
        return $html;
    }

    public function bottomSection() {
        $html='</div></div>';
        return $html;
    }

    public function bodyTestCase($input, $output, $sericeOutput, $failureReason = '') {
        $html = '<div class="card-body jumbotron">
                            <h2><span class="badge badge-primary">Given Input</span></h2>
                            <div class="col-md-12 bg-white text-dark" style="padding:15px 10px">
                                        <pre>'. json_encode($input, JSON_PRETTY_PRINT).'</pre>
                            </div>
                            <div class="col-md-12 ">
                                <div class="row" style="margin:10px -15px">
                                    <div class="col-md-6" >
                                         <h2 style="margin-left: -15px;"><span class="badge badge-primary">Given Output</span></h2>
                                        <div class="bg-white text-dark" style="padding: 15px 11px;margin: 15px -5px 15px -15px;">
                                            <pre>' .json_encode($output, JSON_PRETTY_PRINT). '</pre>
                                        </div>
                                    </div>
                                    <div class="col-md-6" >
                                         <h2 style="margin-left: -5px;"><span class="badge badge-primary">API Output</span></h2>
                                        <div class="bg-white text-dark" style="padding: 15px 11px;margin: 15px -15px 15px -5px;">
                                            <pre>'.json_encode($sericeOutput, JSON_PRETTY_PRINT) . '</pre>
                                        </div>
                                    </div>
                                </div>
                            </div>';

        if (!empty($failureReason)) {
            $html .= '<h2><span class="badge badge-danger">Failure Reason</span></h2>
                            <div class="col-md-12 bg-danger text-white">
                                '.$failureReason.'
                            </div>';
        }
        $html .= '</div>';
        return $html;
    }

    public function pass($index, $title, $input, $output, $serviceOutput) {
        $body = $this->bodyTestCase($input, $output, $serviceOutput);
        $html = '<div class = "card">
        <div class = "card-header bg-success text-center">
        <a class = "card-link text-white" data-toggle = "collapse" href = "#auto'.$index.'">
            '."$index : $title".'
        </a>
        </div>
        <div id = "auto'.$index.'" class = "collapse " data-parent = "#accordion">'
                . $body . '
        </div>';

        return $html;
    }

    public function fail($index, $title, $input, $output, $serviceOutput,$failureReason) {
        $body = $this->bodyTestCase($input, $output, $serviceOutput,$failureReason);
        $html = '<div class = "card">
        <div class = "card-header bg-danger text-center">
        <a class = "card-link text-white" data-toggle = "collapse" href = "#auto'.$index.'">
            '."$index : $title".'
        </a>
        </div>
        <div id = "auto'.$index.'" class = "collapse " data-parent = "#accordion">'
                . $body . '
        </div>';

        return $html;
    }

    public function incomplete($index, $title, $input, $output, $serviceOutput,$failureReason) {
        $body = $this->bodyTestCase($input, $output, $serviceOutput,$failureReason);
        $html = '<div class = "card">
        <div class = "card-header bg-dark text-center">
        <a class = "card-link text-white" data-toggle = "collapse" href = "#auto'.$index.'">
            '."$index : $title".'
        </a>
        </div>
        <div id = "auto'.$index.'" class = "collapse " data-parent = "#accordion">'
                . $body . '
        </div>';

        return $html;
    }

    public function validationFail($index, $title, $input, $output, $serviceOutput,$failureReason) {
        $body = $this->bodyTestCase($input, $output, $serviceOutput,$failureReason);
        $html = '<div class = "card">
        <div class = "card-header bg-warning text-center">
        <a class = "card-link text-dark" data-toggle = "collapse" href = "#auto'.$index.'">
            '."$index : $title".'
        </a>
        </div>
        <div id = "auto'.$index.'" class = "collapse " data-parent = "#accordion">'
                . $body . '
        </div>';

        return $html;
    }

}
